server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 1500
    lease-expiration-duration-in-seconds: 7
  client:
    register-with-eureka: false
    fetch-registry: false