server:
  port: 8080
spring:
  application:
    name: actuator-demo
  output:
    ansi:
      enabled: always
  boot:
    admin:
      client:
#        period: 1000ms
        url: http://127.0.0.1:9990

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://test.com
  #        exclude:
  #          - health
  #          - beans
  endpoint:
    health:
#      show-components: ALWAYS
      show-details: ALWAYS
#      cache:
#        time-to-live: 10m
    env:
      show-values: ALWAYS
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: FULL
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: "${name}"
    group: "${group}"
    version: "${version}"
    description: "${description}"
