server:
  port: 8761

spring:
  application:
    name: discoveryservice
  output:
    ansi:
      enabled: always

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://mylocalapp:8763/eureka
  instance:
    hostname: localhost

---

spring:
  config:
    activate:
      on-profile: eureka3

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  instance:
    hostname: mylocalapp